[package]
name = "ironposh-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = { version = "0.29.0", features = ["event-stream"] }
event-stream = "0.1.1"
vt100 = "0.16.2"
tracing = "0.1"
