use ironposh_macros::{PsDeserialize, PsSerialize};
use typed_builder::TypedBuilder;

#[cfg(feature = "crossterm")]
use crossterm::{cursor, style::Color, terminal};

/// A nested host coordinate pair.
///
/// Derived as a sub-object (no message type): the `#[derive]` generates the
/// `ComplexObject` conversions *and* the `ToPsValue`/`FromPsValue` bridge, so
/// it composes inside [`HostDefaultData`].
#[derive(Debug, Clone, PartialEq, Eq, Default, TypedBuilder, PsSerialize, PsDeserialize)]
pub struct Coordinates {
    #[builder(default = 0)]
    pub x: i32,
    #[builder(default = 0)]
    pub y: i32,
}

/// A nested host size (width/height), derived as a sub-object like
/// [`Coordinates`].
#[derive(Debug, Clone, PartialEq, Eq, Default, PsSerialize, PsDeserialize)]
pub struct Size {
    pub width: i32,
    pub height: i32,
}

/// The PowerShell host's RawUI default data (MS-PSRP §2.2.3.14).
///
/// On the wire this is a `<DCT>` keyed by integer index, where every value is a
/// `{T, V}` object pairing a .NET type name with the value. Both sides are
/// macro-generated by `#[ps(value_dictionary)]` + the per-field `key`/`type_tag`
/// attributes — there is no hand-written `ComplexObject` here.
#[derive(Debug, Clone, PartialEq, Eq, TypedBuilder, PsSerialize, PsDeserialize)]
#[ps(
    value_dictionary,
    type_names("System.Collections.Hashtable", "System.Object")
)]
pub struct HostDefaultData {
    #[builder(default = 7)]
    #[ps(key = 0, type_tag = "System.ConsoleColor")]
    pub foreground_color: i32,
    #[builder(default = 0)]
    #[ps(key = 1, type_tag = "System.ConsoleColor")]
    pub background_color: i32,
    #[builder(default)]
    #[ps(key = 2, type_tag = "System.Management.Automation.Host.Coordinates")]
    pub cursor_position: Coordinates,
    #[builder(default)]
    #[ps(key = 3, type_tag = "System.Management.Automation.Host.Coordinates")]
    pub window_position: Coordinates,
    #[builder(default = 25)]
    #[ps(key = 4, type_tag = "System.Int32")]
    pub cursor_size: i32,
    #[ps(key = 5, type_tag = "System.Management.Automation.Host.Size")]
    pub buffer_size: Size,
    #[ps(key = 6, type_tag = "System.Management.Automation.Host.Size")]
    pub window_size: Size,
    #[ps(key = 7, type_tag = "System.Management.Automation.Host.Size")]
    pub max_window_size: Size,
    #[ps(key = 8, type_tag = "System.Management.Automation.Host.Size")]
    pub max_physical_window_size: Size,
    #[builder(default = "PowerShell".to_string())]
    #[ps(key = 9, type_tag = "System.String")]
    pub window_title: String,
    #[builder(default = "en-US".to_string())]
    #[ps(key = 10, type_tag = "System.String")]
    pub locale: String,
    #[builder(default = "en-US".to_string())]
    #[ps(key = 11, type_tag = "System.String")]
    pub ui_locale: String,
}

impl Default for HostDefaultData {
    /// The default host data PowerShell assumes when none is supplied.
    fn default() -> Self {
        Self {
            foreground_color: 7,
            background_color: 0,
            cursor_position: Coordinates::default(),
            window_position: Coordinates::default(),
            cursor_size: 25,
            buffer_size: Size {
                width: 120,
                height: 3000,
            },
            window_size: Size {
                width: 120,
                height: 50,
            },
            max_window_size: Size {
                width: 120,
                height: 50,
            },
            max_physical_window_size: Size {
                width: 120,
                height: 50,
            },
            window_title: "PowerShell".to_string(),
            locale: "en-US".to_string(),
            ui_locale: "en-US".to_string(),
        }
    }
}

#[cfg(feature = "crossterm")]
fn console_color_to_i32(color: Color) -> i32 {
    match color {
        Color::Black => 0,
        Color::DarkBlue => 1,
        Color::DarkGreen => 2,
        Color::DarkCyan => 3,
        Color::DarkRed => 4,
        Color::DarkMagenta => 5,
        Color::DarkYellow => 6,
        // Map non-16-color values to nearest (Grey as fallback)
        Color::Grey | Color::Rgb { .. } | Color::AnsiValue(_) | Color::Reset => 7,
        Color::DarkGrey => 8,
        Color::Blue => 9,
        Color::Green => 10,
        Color::Cyan => 11,
        Color::Red => 12,
        Color::Magenta => 13,
        Color::Yellow => 14,
        Color::White => 15,
    }
}

impl HostDefaultData {
    /// Creates HostDefaultData from current crossterm terminal state
    ///
    /// Queries the terminal for current cursor position and buffer size,
    /// uses sensible defaults for values crossterm cannot provide.
    ///
    /// # Errors
    ///
    /// Returns error if crossterm fails to query terminal state.
    #[cfg(feature = "crossterm")]
    pub fn from_crossterm() -> Result<Self, std::io::Error> {
        // Query terminal state
        let (cols, rows) = terminal::size()?;
        let (cursor_x, cursor_y) = cursor::position()?;

        // Choose default colors (can be customized by caller)
        let fg_color = Color::Grey; // -> 7
        let bg_color = Color::Black; // -> 0

        // Convert to console color integers
        let foreground_color = console_color_to_i32(fg_color);
        let background_color = console_color_to_i32(bg_color);

        // Convert terminal dimensions to i32
        let cols = cols as i32;
        let rows = rows as i32;
        let x = cursor_x as i32;
        let y = cursor_y as i32;

        Ok(Self {
            foreground_color,
            background_color,
            cursor_position: Coordinates { x, y },
            window_position: Coordinates { x: 0, y: 0 }, // Not exposed by crossterm
            cursor_size: 25,                             // Default cursor size (0-100%)
            buffer_size: Size {
                width: cols,
                height: rows,
            },
            window_size: Size {
                width: cols,
                height: rows,
            },
            max_window_size: Size {
                width: cols,
                height: rows,
            },
            max_physical_window_size: Size {
                width: cols,
                height: rows,
            },
            window_title: "PowerShell".to_string(),
            locale: "en-US".to_string(),
            ui_locale: "en-US".to_string(),
        })
    }
}
